version: 2.1
executors:
  node-executor:
    docker:
      - image: "cimg/node:18.12.0"

commands:
  gatsby-build:
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "./package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm --prefix . install && npm --prefix . run-script clean
      - save_cache:
          key: npm-cache-{{ checksum "./package-lock.json" }}
          paths:
            - ./node_modules
      - restore_cache:
          keys:
            - gatsby-public-cache-{{ .Branch }}
      # - run:
      #    name: Gatsby Test
      #    command: npm run test:unit
      - run:
          name: Gatsby Build
          command: GATSBY_CPU_COUNT=2 npm --prefix . run-script build
      - save_cache:
          key: gatsby-public-cache-{{ .Branch }}
          paths:
            - ./public

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - main
      - release:
          filters:
            branches:
              only:
                - main
jobs:
  build:
    executor: node-executor
    working_directory: ~/repo
    steps:
      - gatsby-build
      - run:
          name: Netlify Deploy
          command: ./node_modules/.bin/netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --dir=./public
  release:
    executor: node-executor
    working_directory: ~/repo
    steps:
      - gatsby-build
      - run:
          name: Netlify Deploy
          command: ./node_modules/.bin/netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --prod --dir=./public
# VS Code Extension Version: 1.5.1
